name: Trigger rebuild
on:
  push:
    branches:
      - main
      
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow Mochi Discord Preview
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/mochi-discord/actions/workflows/gke-preview.yml/dispatches \
           -d '{"ref":"preview"}'
      - name: Trigger workflow Mochi Discord Prod
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/mochi-discord/actions/workflows/gke-prod.yml/dispatches \
           -d '{"ref":"master"}'
      - name: Trigger workflow Mochi Telegram Preview
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/mochi-telegram/actions/workflows/gke-preview.yml/dispatches \
           -d '{"ref":"preview"}'
      - name: Trigger workflow Mochi Telegram Prod
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/mochi-telegram/actions/workflows/gke-prod.yml/dispatches \
           -d '{"ref":"main"}'
      - name: Trigger workflow Tono discord Preview
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/tono-discord/actions/workflows/gke-preview.yml/dispatches \
           -d '{"ref":"preview"}'
      - name: Trigger workflow Tono discord Prod
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/tono-discord/actions/workflows/gke-prod.yml/dispatches \
           -d '{"ref":"main"}'
      - name: Trigger workflow Mochi Web
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/mochi-ui/actions/workflows/deploy-mochi-web.yml/dispatches \
           -d '{"ref":"main"}'

      