name: Trigger rebuild
on:
  push:
    branches:
      - main
      - cicd
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Trigger workflow Mochi Discord Preview
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/consolelabs/mochi-discord/actions/workflows/gke-preview.yml/dispatches \
          -d '{"ref":"preview"}'