name: Trigger rebuild
on:
  push:
    branches:
      - main
      
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow Mochi Discord Preview
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/consolelabs/mochi-discord/actions/workflows/gke-preview.yml/dispatches \
           -d '{"ref":"preview"}'